# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_beta <- function(K, X, E_ridge, y, weights, E_omega, obs_E_prob) {
    .Call('_FactorHet_cpp_beta', PACKAGE = 'FactorHet', K, X, E_ridge, y, weights, E_omega, obs_E_prob)
}

cpp_beta_plain <- function(K, X, omega, ridge, s) {
    .Call('_FactorHet_cpp_beta_plain', PACKAGE = 'FactorHet', K, X, omega, ridge, s)
}

cg_custom <- function(K, X, omega, list_ridge, s, old_beta, weights, tol, it_max = 0L, low_dimension = 5L) {
    .Call('_FactorHet_cg_custom', PACKAGE = 'FactorHet', K, X, omega, list_ridge, s, old_beta, weights, tol, it_max, low_dimension)
}

trace_df_cpp <- function(X, beta, ridge) {
    .Call('_FactorHet_trace_df_cpp', PACKAGE = 'FactorHet', X, beta, ridge)
}

trace_AinvB_sparse <- function(A, B) {
    .Call('_FactorHet_trace_AinvB_sparse', PACKAGE = 'FactorHet', A, B)
}

trace_AinvB <- function(A, B) {
    .Call('_FactorHet_trace_AinvB', PACKAGE = 'FactorHet', A, B)
}

fast_sparse_df <- function(LL, PR) {
    .Call('_FactorHet_fast_sparse_df', PACKAGE = 'FactorHet', LL, PR)
}

cpp_moderator_deriv <- function(W, phi, do_grad = TRUE, do_hess = TRUE, do_ln_hess = TRUE, moderator_grad = TRUE) {
    .Call('_FactorHet_cpp_moderator_deriv', PACKAGE = 'FactorHet', W, phi, do_grad, do_hess, do_ln_hess, moderator_grad)
}

cpp_gradient_phi <- function(par, K, norm_weights, weights_W, group_E_prob, W, ridge_penalty, gamma, rank_F, power_pi, b_r, lambda) {
    .Call('_FactorHet_cpp_gradient_phi', PACKAGE = 'FactorHet', par, K, norm_weights, weights_W, group_E_prob, W, ridge_penalty, gamma, rank_F, power_pi, b_r, lambda)
}

cpp_obj_phi <- function(par, K, norm_weights, weights_W, W, group_E_prob, ridge_penalty, gamma, rank_F, power_pi, b_r, lambda) {
    .Call('_FactorHet_cpp_obj_phi', PACKAGE = 'FactorHet', par, K, norm_weights, weights_W, W, group_E_prob, ridge_penalty, gamma, rank_F, power_pi, b_r, lambda)
}

calculate_nullspace_basis <- function(X) {
    .Call('_FactorHet_calculate_nullspace_basis', PACKAGE = 'FactorHet', X)
}

rank_sparse <- function(X) {
    .Call('_FactorHet_rank_sparse', PACKAGE = 'FactorHet', X)
}

softmax_matrix <- function(X) {
    .Call('_FactorHet_softmax_matrix', PACKAGE = 'FactorHet', X)
}

sparse_diag <- function(m) {
    .Call('_FactorHet_sparse_diag', PACKAGE = 'FactorHet', m)
}

logpi_adjust <- function(X, logpi) {
    .Call('_FactorHet_logpi_adjust', PACKAGE = 'FactorHet', X, logpi)
}

